name: Zephyr Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive   # if using west init in repo

      - name: Setup Zephyr
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: app          # path to your app
          toolchains: arm-zephyr-eabi

      - name: West Update
        run: |
          west update --narrow

      - name: Build for HolyIoT YJ-17095
        run: |
          west build -b holyiot_yj17095 --pristine app -d build
          # Or for blinky sample:
          # west build -b holyiot_yj17095 samples/basic/blinky
