name: Build Firmware

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Zephyr
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: app

      - name: Update West
        run: west update

      - name: Build
        run: |
          west build -s app -b holyiot_yj17095 -d build

      - name: Upload HEX
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            build/zephyr/zephyr.hex
            build/zephyr/zephyr.elf
